"""
Django settings for CallQ project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


class ImmediateFileHandler(logging.FileHandler):
    """FileHandler that flushes after every emit — safe for IIS process recycling.

    Standard FileHandler buffers writes; if IIS recycles the worker process
    before the buffer is flushed the last N log lines are silently lost.
    This subclass calls flush() after each record so every line hits disk immediately.
    """

    def emit(self, record):
        super().emit(record)
        self.flush()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Logging configuration
BASE_LOG_DIR = BASE_DIR / 'CallQ_logs'
today = datetime.now()
year_folder = str(today.year)
month_folder = today.strftime("%B")  
day_folder = f"{today.day:02d}"

LOG_DIR = BASE_LOG_DIR / year_folder / month_folder / day_folder
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'request_hits_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'request_hits.log',
            'formatter': 'verbose',
        },
        'actions_file': {
            'level': 'INFO',
            'class': 'CallQ.settings.ImmediateFileHandler',
            'filename': LOG_DIR / 'actions.log',
            'formatter': 'verbose',
        },
        'fcm_file': {
            'level': 'DEBUG',
            'class': 'CallQ.settings.ImmediateFileHandler',
            'filename': LOG_DIR / 'fcm.log',
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'request_hits': {
            'handlers': ['request_hits_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'actions': {
            'handlers': ['actions_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'fcm': {
            'handlers': ['fcm_file', 'actions_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

APP_VERSION = os.getenv('APP_VERSION')

PROJECT_NAME = os.getenv('PROJECT_NAME')

PROJECT_DISPLAY_NAME = os.getenv('PROJECT_DISPLAY_NAME')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Web Hosting Configuration (IIS/Subfolder support)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', None)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'companydetails',
    'configdetails',
    'userdetails',
    'callq_core',
    'licenses',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CallQ.middleware.LicenseCheckMiddleware',
    'callq_core.middleware.GlobalExceptionMiddleware',
]

ROOT_URLCONF = 'CallQ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'companydetails.context_processors.project_info',
                'companydetails.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'CallQ.wsgi.application'

LICENSE_PORTAL_URL = os.getenv('LICENSE_PORTAL_URL')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

AUTHENTICATION_BACKENDS = [
    'userdetails.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static and Media settings
# Static and Media settings
STATIC_URL = '/CallQ/static/'
FORCE_SCRIPT_NAME = None # Hardcoded in URLs now

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Media files (Images, Videos, Audios)
MEDIA_URL = '/CallQ/media/'
MEDIA_ROOT = BASE_DIR / 'media'


AUTH_USER_MODEL = 'userdetails.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# Session settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 86400  # 1 day in seconds
SESSION_SAVE_EVERY_REQUEST = True


# Email Backend (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Firebase Cloud Messaging (FCM)
FCM_PROJECT_ID = os.getenv('FCM_PROJECT_ID')
_raw_fcm_path = os.getenv('FCM_CREDENTIALS_PATH', '')
# Support both absolute and relative paths (relative resolved from BASE_DIR)
if _raw_fcm_path:
    _fcm_path_obj = Path(_raw_fcm_path)
    FCM_CREDENTIALS_PATH = str(_fcm_path_obj if _fcm_path_obj.is_absolute() else BASE_DIR / _fcm_path_obj)
else:
    FCM_CREDENTIALS_PATH = ''