# Generated by Django 5.2.9 on 2026-04-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companydetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Customer-defined name for easy identification', max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED')], max_length=50)),
                ('token_type', models.CharField(blank=True, choices=[('1_BUTTON', '1 Button'), ('2_BUTTON', '2 Buttons'), ('3_BUTTON', '3 Buttons'), ('4_BUTTON', '4 Buttons')], max_length=50, null=True)),
                ('device_registration_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(default='PC', max_length=100)),
                ('licence_status', models.CharField(default='Pending', max_length=50)),
                ('licence_active_to', models.DateField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('apk_version', models.CharField(blank=True, max_length=50, null=True)),
                ('product_type_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('random_number', models.CharField(default='XXXX', help_text='Random number for token dispenser', max_length=50)),
                ('fcm_token', models.TextField(blank=True, help_text='FCM registration token for push notifications (TV devices)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfigProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED')], max_length=50)),
                ('config_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Config Profile',
                'verbose_name_plural': 'Device Config Profiles',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED')], default='TV', max_length=50)),
                ('config_json', models.JSONField(default=dict)),
                ('day', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_api_sourced', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDeviceCounterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Device ID from external API (e.g., TV001)', max_length=100)),
                ('counter_name', models.CharField(help_text='Counter name from external API', max_length=100)),
                ('api_payload', models.JSONField(default=dict, help_text='Full API request payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Device Counter Log',
                'verbose_name_plural': 'External Device Counter Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('no_of_dispensers', models.IntegerField(default=1)),
                ('no_of_keypads', models.IntegerField(default=1)),
                ('no_of_tvs', models.IntegerField(default=1)),
                ('no_of_brokers', models.IntegerField(default=0)),
                ('no_of_leds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_identifier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_announcement', models.BooleanField(default=False)),
                ('counter_number', models.IntegerField(default=1)),
                ('token_calling', models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=10)),
                ('counter_voice', models.BooleanField(default=False)),
                ('token_voice', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(blank=True, choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED')], default='TV', max_length=50)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TVAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='ad_files/')),
                ('ad_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('token_music_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('audio_language', models.CharField(default='en', max_length=10)),
                ('save_audio_external', models.BooleanField(default=False)),
                ('enable_counter_announcement', models.BooleanField(default=False)),
                ('enable_token_announcement', models.BooleanField(default=False)),
                ('enable_counter_prifix', models.BooleanField(default=False)),
                ('show_ads', models.BooleanField(default=False)),
                ('ad_interval', models.IntegerField(default=5)),
                ('orientation', models.CharField(default='landscape', max_length=20)),
                ('layout_type', models.CharField(default='default', max_length=50)),
                ('display_rows', models.IntegerField(default=3)),
                ('display_columns', models.IntegerField(default=4)),
                ('counter_text_color', models.CharField(default='#000000', max_length=20)),
                ('token_text_color', models.CharField(default='#000000', max_length=20)),
                ('scroll_text_color', models.CharField(default='#000000', max_length=20)),
                ('token_font_size', models.IntegerField(default=24)),
                ('counter_font_size', models.IntegerField(default=24)),
                ('tokens_per_counter', models.IntegerField(default=5)),
                ('no_of_counters', models.IntegerField(default=1)),
                ('no_of_dispensers', models.IntegerField(default=1)),
                ('ad_placement', models.CharField(default='right', max_length=20)),
                ('current_token_color', models.CharField(default='#000000', max_length=20)),
                ('previous_token_color', models.CharField(default='#888888', max_length=20)),
                ('blink_current_token', models.BooleanField(default=False)),
                ('blink_seconds', models.IntegerField(default=1)),
                ('token_format', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default='T1', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_id', models.CharField(max_length=50)),
                ('counter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('counter_code', models.CharField(blank=True, max_length=20, null=True)),
                ('row_span', models.IntegerField(default=1)),
                ('col_span', models.IntegerField(default=1)),
                ('counter_audio_file', models.FileField(blank=True, null=True, upload_to='counter_audios/')),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVCounterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TV Counter Mapping',
                'verbose_name_plural': 'TV Counter Mappings',
                'ordering': ['tv', 'counter'],
            },
        ),
        migrations.CreateModel(
            name='TVDispenserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_index', models.CharField(default='1', help_text="Single ASCII character encoding the dispenser's slot position on this TV. Starts at chr(0x31)='1' and increments through ASCII order (max 90 slots).", max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TV Dispenser Mapping',
                'verbose_name_plural': 'TV Dispenser Mappings',
                'ordering': ['tv', 'button_index'],
            },
        ),
        migrations.CreateModel(
            name='TVKeypadMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypad_index', models.CharField(default='1', help_text="Single ASCII character encoding this keypad's slot position on the TV. Generated via get_button_index_char() — starts at chr(0x31)='1'.", max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TV Keypad Mapping',
                'verbose_name_plural': 'TV Keypad Mappings',
                'ordering': ['tv', 'keypad_index'],
            },
        ),
        migrations.CreateModel(
            name='ButtonMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_button', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companydetails.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companydetails.company')),
                ('dealer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='button_mappings', to='companydetails.dealercustomer')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_json', models.JSONField(default=dict)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('ALL', 'All Days'), ('WKDY', 'Weekdays'), ('WKND', 'Weekends')], default='ALL', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_profiles', to='companydetails.company')),
            ],
            options={
                'ordering': ['device', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(max_length=100)),
                ('counter_number', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='companydetails.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CounterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(help_text='Name of the counter (unique per company)', max_length=100)),
                ('counter_prefix_code', models.CharField(help_text='Prefix used in token generation (unique per company)', max_length=20)),
                ('counter_display_name', models.CharField(help_text='Name shown on TV display', max_length=150)),
                ('max_token_number', models.IntegerField(help_text='Maximum tokens allowed for this counter')),
                ('status', models.BooleanField(default=True, help_text='Active / Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch scope', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_configs', to='companydetails.branch')),
                ('company', models.ForeignKey(help_text='Company that owns this counter', on_delete=django.db.models.deletion.CASCADE, related_name='counter_configs', to='companydetails.company')),
            ],
            options={
                'verbose_name': 'Counter Configuration',
                'verbose_name_plural': 'Counter Configurations',
                'ordering': ['counter_name'],
            },
        ),
        migrations.CreateModel(
            name='CounterTokenDispenserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenser_mappings', to='configdetails.counterconfig')),
            ],
            options={
                'verbose_name': 'Counter Token Dispenser Mapping',
                'verbose_name_plural': 'Counter Token Dispenser Mappings',
                'ordering': ['counter', 'dispenser'],
            },
        ),
    ]
