# Generated by Django 5.2.9 on 2026-04-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companydetails', '0001_initial'),
        ('configdetails', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='licenses.batch'),
        ),
        migrations.AddField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='companydetails.branch'),
        ),
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='companydetails.company'),
        ),
        migrations.AddField(
            model_name='device',
            name='dealer_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='companydetails.dealercustomer'),
        ),
        migrations.AddField(
            model_name='countertokendispensermapping',
            name='dispenser',
            field=models.ForeignKey(limit_choices_to={'device_type': 'TOKEN_DISPENSER'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispenser_counter_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='counter',
            name='assigned_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='configprofile',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_profiles', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='buttonmapping',
            name='source_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='buttonmapping',
            name='target_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='deviceconfigprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_config_profiles', to='companydetails.branch'),
        ),
        migrations.AddField(
            model_name='deviceconfigprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_config_profiles', to='companydetails.company'),
        ),
        migrations.AddField(
            model_name='device',
            name='config_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='configdetails.deviceconfigprofile'),
        ),
        migrations.AddField(
            model_name='embeddedprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedded_profiles', to='companydetails.branch'),
        ),
        migrations.AddField(
            model_name='embeddedprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedded_profiles', to='companydetails.company'),
        ),
        migrations.AddField(
            model_name='device',
            name='embedded_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='configdetails.embeddedprofile'),
        ),
        migrations.AddField(
            model_name='externaldevicecounterlog',
            name='counter',
            field=models.ForeignKey(blank=True, help_text='Mapped counter if found', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_logs', to='configdetails.counterconfig'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companydetails.branch'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='brokers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'device_type': 'BROKER'}, related_name='group_brokers', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companydetails.company'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='dealer_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companydetails.dealercustomer'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='dispensers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'device_type': 'TOKEN_DISPENSER'}, related_name='group_dispensers', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='keypads',
            field=models.ManyToManyField(blank=True, limit_choices_to={'device_type': 'KEYPAD'}, related_name='group_keypads', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='leds',
            field=models.ManyToManyField(blank=True, limit_choices_to={'device_type': 'LED'}, related_name='group_leds', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='tvs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'device_type': 'TV'}, related_name='group_tvs', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='ledconfig',
            name='led',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='led_config', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='ledconfig',
            name='linked_calling_device',
            field=models.ManyToManyField(blank=True, related_name='linked_leds', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companydetails.branch'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_brokers', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companydetails.company'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='dealer_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='companydetails.dealercustomer'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='keypad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_keypads', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='keypad_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_keypads_2', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='keypad_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_keypads_3', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='keypad_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_keypads_4', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='led',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_leds', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='token_dispenser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_tvs', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_sources', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='productionserialnumber',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='configdetails.productionbatch'),
        ),
        migrations.AddField(
            model_name='tvconfig',
            name='tv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv_config', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='tvad',
            name='tv_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='configdetails.tvconfig'),
        ),
        migrations.AddField(
            model_name='tvcounter',
            name='tv_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='configdetails.tvconfig'),
        ),
        migrations.AddField(
            model_name='tvcountermapping',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_mappings', to='configdetails.counterconfig'),
        ),
        migrations.AddField(
            model_name='tvcountermapping',
            name='tv',
            field=models.ForeignKey(limit_choices_to={'device_type': 'TV'}, on_delete=django.db.models.deletion.CASCADE, related_name='tv_counter_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='tvdispensermapping',
            name='dispenser',
            field=models.ForeignKey(limit_choices_to={'device_type': 'TOKEN_DISPENSER'}, on_delete=django.db.models.deletion.CASCADE, related_name='tv_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='tvdispensermapping',
            name='tv',
            field=models.ForeignKey(limit_choices_to={'device_type': 'TV'}, on_delete=django.db.models.deletion.CASCADE, related_name='tv_dispenser_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='tvkeypadmapping',
            name='dispenser',
            field=models.ForeignKey(blank=True, help_text='Token dispenser whose counters Button A on this keypad calls.', limit_choices_to={'device_type': 'TOKEN_DISPENSER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv_keypad_dispenser_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='tvkeypadmapping',
            name='keypad',
            field=models.ForeignKey(limit_choices_to={'device_type': 'KEYPAD'}, on_delete=django.db.models.deletion.CASCADE, related_name='tv_keypad_tv_mappings', to='configdetails.device'),
        ),
        migrations.AddField(
            model_name='tvkeypadmapping',
            name='tv',
            field=models.ForeignKey(limit_choices_to={'device_type': 'TV'}, on_delete=django.db.models.deletion.CASCADE, related_name='tv_keypad_mappings', to='configdetails.device'),
        ),
        migrations.AlterUniqueTogether(
            name='counterconfig',
            unique_together={('company', 'counter_name'), ('company', 'counter_prefix_code')},
        ),
        migrations.AlterUniqueTogether(
            name='countertokendispensermapping',
            unique_together={('counter', 'dispenser')},
        ),
        migrations.AddIndex(
            model_name='externaldevicecounterlog',
            index=models.Index(fields=['device_id', '-created_at'], name='configdetai_device__013bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='externaldevicecounterlog',
            index=models.Index(fields=['counter_name'], name='configdetai_counter_1ae63c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tvcountermapping',
            unique_together={('tv', 'counter')},
        ),
        migrations.AlterUniqueTogether(
            name='tvdispensermapping',
            unique_together={('tv', 'dispenser')},
        ),
        migrations.AlterUniqueTogether(
            name='tvkeypadmapping',
            unique_together={('tv', 'keypad')},
        ),
    ]
