# Generated by Django 5.2.9 on 2026-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_message', models.TextField(help_text='The raw token message received from the device')),
                ('received_dateTime', models.DateTimeField(help_text='Timestamp when the message was received by the server')),
                ('displayed_dateTime', models.DateTimeField(blank=True, help_text='Timestamp when the token was displayed on the TV/display device', null=True)),
                ('customerId', models.CharField(help_text='Customer ID (company_id or dealer customer_id)', max_length=100)),
                ('mac_address', models.CharField(help_text='MAC address of the originating device', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Report',
                'verbose_name_plural': 'Token Reports',
                'ordering': ['-received_dateTime'],
                'indexes': [models.Index(fields=['customerId', '-received_dateTime'], name='configdetai_custome_7e8382_idx'), models.Index(fields=['mac_address', '-received_dateTime'], name='configdetai_mac_add_b14aa5_idx')],
            },
        ),
    ]
