# Generated by Django 5.2.9 on 2026-05-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0006_productionserialnumber_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcounterbuttonmapping',
            name='button_index',
            field=models.CharField(help_text="Group-wide sequential ASCII button index for this counter.  Starts at chr(0x31)='1' for the first counter in the group and increments through the full 74-slot sequence without resetting between dispensers.  Generated via get_button_index_char().", max_length=1),
        ),
        migrations.CreateModel(
            name='VipTokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_from', models.IntegerField(default=1, help_text='First VIP token number (inclusive)')),
                ('vip_to', models.IntegerField(default=999, help_text='Last VIP token number (inclusive)')),
                ('current_token', models.IntegerField(default=0, help_text='Last issued VIP token number (0 = none issued yet).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_token_counters', to='configdetails.counterconfig')),
                ('dispenser', models.ForeignKey(limit_choices_to={'device_type': 'TOKEN_DISPENSER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vip_token_counters', to='configdetails.device')),
            ],
            options={
                'verbose_name': 'VIP Token Counter',
                'verbose_name_plural': 'VIP Token Counters',
                'unique_together': {('counter', 'dispenser')},
            },
        ),
    ]
