# Generated by Django 5.2.9 on 2026-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0007_alter_groupcounterbuttonmapping_button_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='keypad_index',
            field=models.CharField(blank=True, help_text='Globally unique keypad index within a group, assigned only once at group creation.', max_length=1, null=True),
        ),
    ]
