# Generated by Django 5.2.9 on 2026-06-01 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0008_device_keypad_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedDeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SB', models.IntegerField(help_text='Sound/Bell mode: 0 (Bell), 1 (MY sound module), or 2 (New Sil audio module)')),
                ('DT', models.IntegerField(help_text='Display Type: 1 (Single counter), 2 (Double counter), or 4 (Four counter)')),
                ('ND', models.IntegerField(help_text='Number of Digits: 3 or 4')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(limit_choices_to={'device_type': 'LED'}, on_delete=django.db.models.deletion.CASCADE, related_name='led_device_config', to='configdetails.device')),
            ],
            options={
                'verbose_name': 'LED Device Config',
                'verbose_name_plural': 'LED Device Configs',
            },
        ),
    ]
