# Generated by Django 5.2.9 on 2026-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0009_led_device_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedDeviceConfig',
        ),
    ]
