# Generated by Django 5.2.9 on 2026-06-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0010_drop_led_device_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED'), ('Serial Apk', 'Serial Apk'), ('Config Apk', 'Config Apk')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='device_type',
            field=models.CharField(blank=True, choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED'), ('Serial Apk', 'Serial Apk'), ('Config Apk', 'Config Apk')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productionserialnumber',
            name='device_type',
            field=models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker'), ('LED', 'LED'), ('Serial Apk', 'Serial Apk'), ('Config Apk', 'Config Apk')], default='TV', max_length=50),
        ),
    ]
