# Generated by Django 5.2.9 on 2026-06-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0002_initial'),
        ('configdetails', '0011_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmapping',
            options={'verbose_name': 'Group Mapping', 'verbose_name_plural': 'Group Mappings'},
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='groupmapping',
            unique_together={('company', 'group_name')},
        ),
    ]
