# Generated by Django 5.2.9 on 2026-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configdetails', '0012_groupmapping_unique_name_per_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='viptokencounter',
            name='last_reset_date',
            field=models.DateField(blank=True, help_text='Date on which current_token was last reset to vip_from. Used to trigger the automatic daily reset.', null=True),
        ),
    ]
