# Generated by Django 5.2.9 on 2026-06-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0004_branch_unique_together'),
        ('configdetails', '0019_fix_counterconfig_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCounterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Counter Mapping',
                'verbose_name_plural': 'Customer Counter Mappings',
                'ordering': ['counter__counter_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dispenserkeypadmapping',
            options={'ordering': ['group', 'dispenser', 'dispenser_button_index'], 'verbose_name': 'Dispenser → Keypad Mapping', 'verbose_name_plural': 'Dispenser → Keypad Mappings'},
        ),
        migrations.RenameIndex(
            model_name='mqtttokenlog',
            new_name='configdetai_custome_eea4c8_idx',
            old_name='mqtt_cust_recv_idx',
        ),
        migrations.RenameIndex(
            model_name='mqtttokenlog',
            new_name='configdetai_keypad__30698f_idx',
            old_name='mqtt_kp_recv_idx',
        ),
        migrations.RenameIndex(
            model_name='mqtttokenlog',
            new_name='configdetai_is_vali_407875_idx',
            old_name='mqtt_valid_dup_idx',
        ),
        migrations.AlterField(
            model_name='keypadcountermapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='customercountermapping',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_mappings', to='configdetails.counterconfig'),
        ),
        migrations.AddField(
            model_name='customercountermapping',
            name='dealer_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_mappings', to='companydetails.dealercustomer'),
        ),
        migrations.AlterUniqueTogether(
            name='customercountermapping',
            unique_together={('dealer_customer', 'counter')},
        ),
    ]
