# Generated by Django 5.2.9 on 2026-04-29 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companydetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('TV', 'TV'), ('TOKEN_DISPENSER', 'Token Dispenser'), ('KEYPAD', 'Keypad'), ('BROKER', 'Broker')], max_length=50)),
                ('license_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked')], default='INACTIVE', max_length=20)),
                ('device_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_tvs', models.IntegerField(default=0)),
                ('max_dispensers', models.IntegerField(default=0)),
                ('max_keypads', models.IntegerField(default=0)),
                ('max_brokers', models.IntegerField(default=0)),
                ('max_leds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='companydetails.company')),
                ('dealer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='companydetails.dealercustomer')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='BatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('DEALER', 'Dealer'), ('DEALER_CUSTOMER', 'Dealer Customer')], max_length=20)),
                ('requested_tvs', models.IntegerField(default=0)),
                ('requested_dispensers', models.IntegerField(default=0)),
                ('requested_keypads', models.IntegerField(default=0)),
                ('requested_brokers', models.IntegerField(default=0)),
                ('requested_leds', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='licenses.batch')),
                ('dealer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_requests', to='companydetails.dealercustomer')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_requests', to='companydetails.company')),
            ],
            options={
                'verbose_name': 'Batch Request',
                'verbose_name_plural': 'Batch Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
