# Generated by Django 5.2.9 on 2026-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_status', models.CharField(max_length=100)),
                ('product_registration_id', models.IntegerField()),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('number_of_licence', models.IntegerField()),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(choices=[('CUSTOMER', 'Direct Customer'), ('DEALER', 'Dealer')], default='CUSTOMER', max_length=20)),
                ('is_dealer_created', models.BooleanField(default=False)),
                ('branch_configuration', models.CharField(choices=[('SINGLE', 'Single Branch'), ('MULTIPLE', 'Multiple Branches')], default='MULTIPLE', max_length=20)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('number_of_licence', models.IntegerField(default=1)),
                ('noof_broker_devices', models.IntegerField(default=0)),
                ('noof_token_dispensors', models.IntegerField(default=0)),
                ('noof_keypad_devices', models.IntegerField(default=0)),
                ('noof_television_devices', models.IntegerField(default=0)),
                ('noof_led_devices', models.IntegerField(default=0)),
                ('authentication_status', models.CharField(blank=True, max_length=100, null=True)),
                ('product_registration_id', models.IntegerField(blank=True, null=True)),
                ('unique_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('product_from_date', models.DateField(blank=True, null=True)),
                ('product_to_date', models.DateField(blank=True, null=True)),
                ('ads_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dealer Customer',
                'verbose_name_plural': 'Dealer Customers',
                'db_table': 'dealer_customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
