# Generated by Django 5.2.9 on 2026-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='noof_config_apk',
            field=models.IntegerField(default=0, help_text='Max Config APK devices allowed by license'),
        ),
    ]
